version: '3.7'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./site-configs:/etc/nginx/conf.d
      - ./www:/var/www/html
    restart: always
